### ISSUE TITLE
How can I change the default running host to 0.0.0.0 ?

### ISSUE THREAD

**Issue by TotoB12** [abdullahalshawafi/Mathemati_#10]
I am trying to run the app on Replit, and have to set the host to 0.0.0.0 to be able to use it.

Thanks!

**Comment by abdullahalshawafi** [comment]
Hello, @TotoB12. I found this [tutorial](https://replit.com/talk/learn/Flask-Tutorial-Part-1-the-basics/26272#step-2:-setup) on Replit if you haven't checked it out yet.
All you have to do is the following change at the end of the `app.py` file
```
if __name__ == "__main__":
	app.run(
		host='0.0.0.0',
		port=random.randint(2000, 9000)
	)
```
I hope this fixes your problem 😄
Thanks for reaching out!
